### ISSUE TITLE
ZonedDateTime.now to ZonedDateTime.now()

### ISSUE THREAD

**Issue by tkawachi** [opt-tech/chronoscala#10]
ZonedDateTime.now is impure (has side effect). I feel more natural to add a paren to a declaration of an impure function.

**Comment by tkawachi** [comment]
I know it aimed to be a port of nscala-time and this is different from nscala-time. I'm willing to create PR if you agree with this change.

**Comment by sh0hei** [comment]
`chronoscala` is `A port of nscala_time to JSR-310.` for certain.
But I'd like to take better code and idea in aggressively.

I'm waiting for your PR 👍

**Comment by xuwei-k** [comment]
> chronoscala is A port of nscala_time to JSR-310. for certain.
> But

Why `But` ? see https://github.com/nscala-time/nscala-time/commit/12c856bc76d1817a57a84f2c64655e4c6f01597f

**Comment by sh0hei** [comment]
@xuwei-k Thanks your comment. `nscala-time` use parenthesis with impure function for certain as you say.

@tkawachi I'm waiting for your PR.

**Comment by tkawachi** [comment]
I didn't notice such nscala-time parens... OK, I'll work on this.
